<?
session_start();
define("APP_ID",'53545980');
define("APP_SECRET",'1Maasuv2vHnJO3AOaKFC');
define("REDIRECT_URI",'http://Laba29/auth.php');
define("URL_ACCESS_TOKEN",'https://oauth.vk.com/access_token');
define("URL_AUTH",'http://oauth.vk.com/authorize');
define("URL_GET_USER",'https://api.vk.com/method/users.get');
define("API_VERSION",'5.131');
?>